"""RVC (Retrieval-based Voice Conversion) — applies user's cloned voice to any language."""
import os
import base64
import tempfile
import time

try:
    import torch
    TORCH_AVAILABLE = True
except ImportError:
    TORCH_AVAILABLE = False

try:
    # RVC can be imported from various packages
    from rvc_infer import RVCInfer
    RVC_AVAILABLE = True
except ImportError:
    try:
        from rvc.infer import RVCInfer
        RVC_AVAILABLE = True
    except ImportError:
        RVC_AVAILABLE = False
        print("[RVC] Warning: RVC not installed. Install via: pip install rvc-infer")


class RVCService:
    """
    Retrieval-based Voice Conversion service.

    The "bridge" that makes any language sound like the user.
    Takes audio generated by MeloTTS (in any language) and converts
    the voice identity to match the user's cloned voice.
    """

    def __init__(self, model_path=None):
        self.available = False
        self.model = None
        self.model_path = model_path or os.getenv('RVC_MODEL_PATH', './models/rvc')
        self.device = 'cuda' if (TORCH_AVAILABLE and torch.cuda.is_available()) else 'cpu'

        # Create model directory
        os.makedirs(self.model_path, exist_ok=True)

        if not RVC_AVAILABLE:
            print("[RVC] Library not available, service disabled")
            return

        try:
            print("[RVC] RVC service initialized")
            self.available = True
        except Exception as e:
            print(f"[RVC] Failed to initialize: {e}")
            self.available = False

    def convert_voice(self, audio_bytes, user_voice_model_path, pitch_shift=0):
        """
        Apply user's voice identity to base audio.

        Args:
            audio_bytes: Raw audio bytes (from MeloTTS output)
            user_voice_model_path: Path to user's trained RVC model (.pth)
            pitch_shift: Semitone pitch adjustment (-12 to 12)

        Returns:
            str: Base64-encoded audio with user's voice, or None on failure
        """
        if not self.available:
            print("[RVC] Service not available")
            return None

        if not user_voice_model_path or not os.path.exists(user_voice_model_path):
            print(f"[RVC] User voice model not found: {user_voice_model_path}")
            return None

        try:
            print(f"[RVC] Converting voice with model: {user_voice_model_path}")

            # Save input audio to temp file
            input_path = tempfile.mktemp(suffix='.wav')
            with open(input_path, 'wb') as f:
                f.write(audio_bytes)

            output_path = tempfile.mktemp(suffix='.wav')

            # Run RVC inference
            pitch_shift = max(-12, min(12, pitch_shift))

            infer = RVCInfer(
                model_path=user_voice_model_path,
                device=self.device
            )
            infer.convert(
                input_path=input_path,
                output_path=output_path,
                pitch_shift=pitch_shift
            )

            # Read output
            with open(output_path, 'rb') as f:
                converted_bytes = f.read()

            # Cleanup
            for p in [input_path, output_path]:
                try:
                    os.remove(p)
                except Exception:
                    pass

            audio_b64 = base64.b64encode(converted_bytes).decode('utf-8')
            print(f"[RVC] Voice conversion complete ({len(converted_bytes)} bytes)")
            return audio_b64

        except Exception as e:
            print(f"[RVC] Conversion error: {e}")
            return None

    def train_voice_model(self, audio_samples, user_id, epochs=50):
        """
        Train an RVC model from user's voice samples.

        Args:
            audio_samples: List of audio file paths or bytes
            user_id: User identifier
            epochs: Training epochs (default 50, more = better but slower)

        Returns:
            dict: {model_path, training_time, status} or None on failure
        """
        if not self.available:
            print("[RVC] Service not available for training")
            return None

        user_model_dir = os.path.join(self.model_path, user_id)
        os.makedirs(user_model_dir, exist_ok=True)
        model_output_path = os.path.join(user_model_dir, 'model.pth')

        try:
            print(f"[RVC] Training voice model for user {user_id} ({epochs} epochs)...")
            start_time = time.time()

            # Save audio samples to temp directory
            sample_dir = os.path.join(user_model_dir, 'samples')
            os.makedirs(sample_dir, exist_ok=True)

            for i, sample in enumerate(audio_samples):
                sample_path = os.path.join(sample_dir, f'sample_{i}.wav')
                if isinstance(sample, bytes):
                    with open(sample_path, 'wb') as f:
                        f.write(sample)
                elif isinstance(sample, str) and os.path.exists(sample):
                    import shutil
                    shutil.copy2(sample, sample_path)

            # Train RVC model
            # Note: Actual RVC training requires specific pipeline setup
            # This is the integration point for the RVC training CLI
            try:
                from rvc_infer import RVCTrainer
                trainer = RVCTrainer(device=self.device)
                trainer.train(
                    dataset_path=sample_dir,
                    model_name=user_id,
                    output_path=model_output_path,
                    epochs=epochs
                )
            except ImportError:
                print("[RVC] RVC training module not available")
                print("[RVC] To train models, use the RVC WebUI or CLI separately")
                return {
                    'model_path': None,
                    'training_time': 0,
                    'status': 'training_module_not_available',
                    'message': 'Install RVC training tools to enable voice model training'
                }

            training_time = time.time() - start_time
            print(f"[RVC] Training complete in {training_time:.1f}s")

            return {
                'model_path': model_output_path,
                'training_time': round(training_time, 2),
                'status': 'completed'
            }

        except Exception as e:
            print(f"[RVC] Training error: {e}")
            return {
                'model_path': None,
                'training_time': 0,
                'status': 'error',
                'message': str(e)
            }

    def get_user_model_path(self, user_id):
        """Get path to user's trained RVC model, or None if not trained."""
        model_path = os.path.join(self.model_path, user_id, 'model.pth')
        if os.path.exists(model_path):
            return model_path
        return None

    def health_check(self):
        return self.available

    def unload(self):
        if self.model is not None:
            try:
                del self.model
                self.model = None
                if TORCH_AVAILABLE and torch.cuda.is_available():
                    torch.cuda.empty_cache()
                print("[RVC] Model unloaded")
            except Exception as e:
                print(f"[RVC] Error unloading: {e}")
